# Generated by Django 4.2.3 on 2023-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolFees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_balance',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee_payments',
            name='payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
