# Generated by Django 4.2.3 on 2023-07-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_students_telphone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='date_of_allocation',
            new_name='date_of_reg',
        ),
    ]
