# Generated by Django 4.2.3 on 2023-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_date_of_allocation_students_date_of_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='telphone_no',
        ),
        migrations.AddField(
            model_name='students',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
