# Generated by Django 4.2.3 on 2023-07-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_students_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelallocation',
            name='hostel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.hostels'),
            preserve_default=False,
        ),
    ]
