# Generated by Django 4.2.3 on 2023-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_hostelallocation_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
