# Generated by Django 4.2.3 on 2023-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_students_date_of_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_reg',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
