# Generated by Django 4.2.3 on 2023-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_hostelallocation_hostel_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='hostel_allocation',
            field=models.BooleanField(default=True),
        ),
    ]
