# Generated by Django 4.2.3 on 2023-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_hostelallocation_hostel_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='hostel_allocation',
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_reg',
            field=models.DateField(auto_now=True),
        ),
    ]
