# Generated by Django 4.2.3 on 2023-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_hostelallocation_hostel_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelallocation',
            name='date_of_allocation',
            field=models.DateField(auto_now=True),
        ),
    ]
